title: Robert aka 'revox'
description: A 22 year old IT & electronics enthusiast.
url: "https://piotrowsky.dev"
future: true
google_analytics: G-X4VXZH17KC
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag